### ISSUE TITLE
Does not work with npm

### ISSUE THREAD

**Issue by benmccann** [navneetsharmaui/sveltekit-starter#3] opened 2021-04-09 00:38 UTC
`npm install` fails with:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: sveltetron-9000@0.0.1
npm ERR! Found: svelte-loader@3.1.0
npm ERR! node_modules/svelte-loader
npm ERR!   dev svelte-loader@"^3.0.0" from the root project
npm ERR!   peer svelte-loader@"*" from @storybook/svelte@6.2.3
npm ERR!   node_modules/@storybook/svelte
npm ERR!     dev @storybook/svelte@"^6.2.2" from the root project
npm ERR!     peer @storybook/svelte@"^6.1.20" from @storybook/addon-svelte-csf@1.0.0
npm ERR!     node_modules/@storybook/addon-svelte-csf
npm ERR!       dev @storybook/addon-svelte-csf@"^1.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer svelte-loader@"^2.9.1" from @storybook/addon-svelte-csf@1.0.0
npm ERR! node_modules/@storybook/addon-svelte-csf
npm ERR!   dev @storybook/addon-svelte-csf@"^1.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See ~/.npm/eresolve-report.txt for a full report.
```

It looks like https://github.com/storybookjs/addon-svelte-csf/pull/19 would fix this

**Comment by navneetsharmaui** [comment] 2021-04-09 06:34
Yes, I had built the project with keeping Yarn caching in Mind. I thought many people might already be using the Yarn and Yarn 2 to provide a great setup. I will also create a separate branch where the NPM specific setup could be done

**Comment by benmccann** [comment] 2021-04-09 13:28
It seems like it will be hard to maintain a separate branch and would be easier to just make `master` work with both

**Comment by navneetsharmaui** [comment] 2021-04-09 14:56
@benmccann that's right, I will first try to resolve the issue of npm in a separate branch once stable and this works in conjunction with Yarn and Yarn 2, I will merge that with the master/main

**Comment by navneetsharmaui** [comment] 2021-04-09 20:37
@benmccann I tried the project with npm it's working fine and as expected. For now I'm closing down the issue please let me know if the issue persist.

**Comment by benmccann** [comment] 2021-04-09 23:35
It's still failing for me. I'm on npm 7.8.0. Perhaps you have an older version?

**Comment by navneetsharmaui** [comment] 2021-04-10 06:09
@benmccann Yes I had 6.X version of npm and after upgrading to 7.9.0 it's also not working for me

**Comment by navneetsharmaui** [comment] 2021-09-07 20:06
@benmccann The latest repo is working with the npm now. Please check it if the issue is still there for you.

**Closed by navneetsharmaui** 2021-09-07 20:06 UTC
